### ISSUE TITLE
The exploration constant

### ISSUE THREAD

**Issue by gbyuHub** [namoshizun/PyPOMDP#5]
Hi, good work first! A small concern is about the exploration constant _c_, which should be _c_ = R_hi - R_lo in the original paper of POMCP. But it seems you use a fixed value here, is it correct?

**Comment by namoshizun** [comment]
Thx @FisherguanbaoYu  ! The dynamic exploration parameter was used in the Experiments in the original paper, which I guess was a little improvement to the original UCB1. In the standard / naive UCB1 formulation, the `c` was set out to be a non-changing constant But surely it is encouraged to fine tune those parameters or make them dynamic / reactive to the observed environment :D.
